version: '3'

services:
   db:
     container_name: ${CONTAINER_NAME}.mysql
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql/
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   prestashop:
     depends_on:
       - db
     container_name: ${CONTAINER_NAME}
     image: prestashop/prestashop:1.7-7.2-apache
     restart: unless-stopped
     volumes:
       - ${CORE_PATH}:/var/www/html/
     environment:
       PS_DEV_MODE: ${PS_DEV_MODE}
       PS_HOST_MODE: ${PS_HOST_MODE}
       PS_DEMO_MODE: ${PS_DEMO_MODE}
       DB_SERVER: ${CONTAINER_NAME}.mysql
       DB_USER: ${MYSQL_USER}
       DB_PASSWD: ${MYSQL_PASSWORD}
       DB_PREFIX: ${DB_PREFIX}
       DB_NAME: ${MYSQL_DATABASE}
       PS_INSTALL_AUTO: ${PS_INSTALL_AUTO}
       PS_ERASE_DB: ${PS_ERASE_DB}
       PS_DOMAIN: ${DOMAINS}
       PS_LANGUAGE: ${PS_LANGUAGE}
       PS_COUNTRY: ${PS_COUNTRY}
       PS_ALL_LANGUAGES: ${PS_ALL_LANGUAGES}
       PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
       PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
       PS_ENABLE_SSL: ${PS_ENABLE_SSL}
       ADMIN_MAIL: ${ADMIN_MAIL}
       ADMIN_PASSWD: ${ADMIN_PASSWD}
       PS_HANDLE_DYNAMIC_DOMAIN: ${PS_HANDLE_DYNAMIC_DOMAIN}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}